# ---------------------------------------------
# Project Configuration
# ---------------------------------------------

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

drupal_build_composer_project: false
drupal_install_site: false

# Enable to only run tasks that are required for new projects.
projects_only_provision: false

# ---------------------------------------------
# Installed Extras
# ---------------------------------------------


# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - unzip
  - htop
  - libnotify-bin
  - pv
  - sqlite
  - tmux
  - libnss3
  - libasound2

# ---------------------------------------------
# Installed Extra: NodeJS
# ---------------------------------------------

# `nodejs` must be in installed_extras for this to work.
nodejs_npm_global_packages:
  - name: bower
  - name: gulp
  - name: grunt
  - name: yarn


# ---------------------------------------------
# Installed Extra: Ruby
# ---------------------------------------------

# `ruby` must be in installed_extras for this to work.
ruby_install_gems: ['bundler']

# ---------------------------------------------
# PHP Configuration Overrides
# ---------------------------------------------

php_version: "7.2"
# php_packages:
#   - php5
#   - php5-apcu
#   - php5-mcrypt
#   - php5-cli
#   - php5-common
#   - php5-curl
#   - php5-dev
#   - php5-fpm
#   - php5-gd
#   - php5-sqlite
#   - php-pear
#   - libpcre3-dev
# php_conf_paths:
#   - /etc/php5/fpm
#   - /etc/php5/apache2
#   - /etc/php5/cli
# php_extension_conf_paths:
#   - /etc/php5/fpm/conf.d
#   - /etc/php5/apache2/conf.d
#   - /etc/php5/cli/conf.d
# php_fpm_daemon: php5-fpm
# php_fpm_conf_path: "/etc/php5/fpm"
# php_fpm_pool_conf_path: "/etc/php5/fpm/pool.d/www.conf"
# php_mysql_package: php5-mysql


# ---------------------------------------------
# Firewall & Security
# ---------------------------------------------

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
  - "3000" #browsersync

# ---------------------------------------------
# Core VM Configuration
# ---------------------------------------------

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

vagrant_synced_folders:
- local_path: ~/Sites/drupalvm-alpha
  destination: /var/www
  type: nfs
  create: true
